### ISSUE TITLE
problem when creating a video with a batch of images

### ISSUE THREAD

**Issue by PaprikaSheen** [Scholar01/sd-webui-mov2mov#103]
problem when creating a video with a batch of images
![imagen](https://github.com/Scholar01/sd-webui-mov2mov/assets/147209249/f438a251-3dcd-480d-8b69-77cc361c2add)

**Comment by tophboogie** [comment]
I'm seeing the exact same error on ubuntu 22.04.2 LTS

ffmpeg: 4.4.2-0ubuntu0.22.04.1
python: 3.10.12
automatic1111: v1.6.0

Any clues on what is happening here greatly appreciated :)

**Comment by NDBXQ** [comment]
<img width="708" alt="截屏2023-10-13 17 53 13" src="https://github.com/Scholar01/sd-webui-mov2mov/assets/104010956/53233150-422e-4364-ae44-b2db20f240ab">

Change this part of the code in file -->stable-diffusion-webui/extensions/sd-webui-mov2mov/scripts/m2m_util.py

**Comment by PaprikaSheen** [comment]
> <img alt="截屏2023-10-13 17 53 13" width="708" src="https://user-images.githubusercontent.com/104010956/274866790-53233150-422e-4364-ae44-b2db20f240ab.png">
> 
> Change this part of the code in file -->stable-diffusion-webui/extensions/sd-webui-mov2mov/scripts/m2m_util.py

worked for me
