### ISSUE TITLE
Has the audio of the video been lost?

### ISSUE THREAD

**Issue by bh4rep** [Scholar01/sd-webui-mov2mov#111]
The original video has dubbing, but the video generated after processing with mov2mov has no sound. How can we solve this problem?

**Comment by Ferocit** [comment]
A manual way for now would be to extract the audio from the original clip and add it to the new clip. With ffmpeg it works for me this way:

Extract sound:
`ffmpeg -i original_video.mp4 -vn -acodec copy output-audio.aac`

Add sound:
`ffmpeg -i new_video.mp4 -i output-audio.aac -map 0:v -map 1:a -c:v copy -shortest output.mp4`
