### ISSUE TITLE
求教：我是用咱们mov2mov视频换装很不稳

### ISSUE THREAD

**Issue by wangwenjie1314** [Scholar01/sd-webui-mov2mov#129]
作者，你好，我用了下mov2mov 视频换脸很稳，但是我想给视频换装很不稳，有没有一些方法或者特殊操作，我弄了2天总是做不出稳定换装效果，期待您的回复，谢谢了

视频换脸效果：
提示词引导系数 (CFG Scale) 10
重绘幅度 Denoising strength  0.3
![image](https://github.com/Scholar01/sd-webui-mov2mov/assets/4018406/3ae67e06-440f-4754-9df7-315abc8238a5)

视频换装效果：
提示词引导系数 (CFG Scale) 尝试了 15 、20、30
重绘幅度 Denoising strength  尝试了 0.4、0.5、0.6、0.75
效果都不太好
![image](https://github.com/Scholar01/sd-webui-mov2mov/assets/4018406/123ab821-5dc1-48fd-a787-6672a76b4723)
![image](https://github.com/Scholar01/sd-webui-mov2mov/assets/4018406/871e0006-2d93-491f-b889-c2fd698a5435)

期待您的回复

**Comment by wwwtxhy** [comment]
haha,can't

**Comment by wangwenjie1314** [comment]
后面我解决了，不用mov2mov，改用的ebs方案，比较稳定，还能换装
