### ISSUE TITLE
已安裝opencv，跑到最後輸出影片時會報錯

### ISSUE THREAD

**Issue by Grasseed** [Scholar01/sd-webui-mov2mov#13]
[ERROR:1@50223.527] global /build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2985) open Could not open codec libopenh264, error: Unspecified error (-22)
[ERROR:1@50223.527] global /build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (3002) open VIDEOIO/FFMPEG: Failed to initialize VideoWriter

**Comment by Scholar01** [comment]
ffmpeg需要安装一下，或者点别的格式
