### ISSUE TITLE
bug，视频变长

### ISSUE THREAD

**Issue by Laidawang** [Scholar01/sd-webui-mov2mov#15]
发现不良的帧率选择可能导致视频变长。感觉是这里的取整原因。
![image](https://user-images.githubusercontent.com/85244566/223347413-74a38d32-ccb5-4389-bd53-247eb250d5a0.png)

**Comment by yizhan** [comment]
就如果这个原视频是50HZ 但是在生成视频的时候在mov2mov中选30 Movie Frames 最后生成时间会变长
