### ISSUE TITLE
按照教程安装完成之后，扩展里面找不到怎么回事

### ISSUE THREAD

**Issue by zzwzl1** [Scholar01/sd-webui-mov2mov#24]
按照教程安装完成之后，扩展里面找不到怎么回事

**Comment by ZJJHYM** [comment]
我也是，安装好了之后，在img2img中找不到，但是显示是说安装好了

**Comment by zhouhao27** [comment]
我也是同样问题。

<img width="675" alt="Screenshot 2023-03-14 at 8 54 42 PM" src="https://user-images.githubusercontent.com/8099731/225007211-2ec7ea63-41d8-4402-8510-46706a7b1efa.png">
<img width="718" alt="Screenshot 2023-03-14 at 8 54 49 PM" src="https://user-images.githubusercontent.com/8099731/225007248-f940e8e7-376c-4936-8e3c-5d9a076a9879.png">

**Comment by ykk648** [comment]
啊这 在和img2img同级别的tag里面，往右看。。

**Comment by zark119** [comment]
同样的问题，没有在图生图里出现这个选项

**Comment by Louis24** [comment]
![image](https://github.com/Scholar01/sd-webui-mov2mov/assets/18719360/1cb0211e-a0d6-43b9-9b65-2aa91687a233)
 没有
