### ISSUE TITLE
生成的文件大小始终只有几k

### ISSUE THREAD

**Issue by WeiWenxing** [Scholar01/sd-webui-mov2mov#26]
一切都正常，只有最终生成的视频大小是几k， 修改分辨率可以正常，但是这是不对的，我的视频文件是1080_1920, 我把输出设置成540_960就是正常等比例缩放。

但是这样的分辨率总是出问题，查看到生成的图片是536_960的，而opencv参数是540_960，这就始终无法生成视频。 我把生成视频的代码修改一下，可以成功。
def images_to_video(images, frames, mode, w, h, out_path):
    fourcc = cv2.VideoWriter_fourcc(*mode)
/* 添加的代码， 开始 */
    if len(images) > 0:
        img = images[0]
        img_width, img_height= img.size
        w = img_width
        h = img_height
/* 添加的代码， 结束 */
    video = cv2.VideoWriter(out_path, fourcc, frames, (w, h))
    for i, image in enumerate(images):
        img = cv2.cvtColor(numpy.asarray(image), cv2.COLOR_RGB2BGR)
        video.write(img)
        print("Processed frame {} - Frame {}, w_{} x h_{}, out_path::{}".format(image, i, w, h, out_path))
    video.release()

    return out_path

**Comment by Scholar01** [comment]
已经并入代码,实在感谢!!

**Comment by jackiezhang11** [comment]
加上face editor 后，不能生成视频。请问这个有解决办法吗
