### ISSUE TITLE
 0。0。8，colab下运行，在保存视频时会提示找不到文件或目录

### ISSUE THREAD

**Issue by lloydsun** [Scholar01/sd-webui-mov2mov#29]
outputs/mov2mov-images

能看到生成的图片

但是

outputs/mov2mov-videos

下就什么都没有，终端中提示找不到 outputs/mov2mov-videos/xxx.mp4

**Comment by caojiurui** [comment]
Start parsing the number of mov frames
The video conversion is completed, images:355
current progress: 1/1
Loading model from cache: control_openpose-fp16 [9ca67cc5]
Loading preprocessor: openpose_hand
  0% 0/7 [00:00<?, ?it/s]
 14% 1/7 [00:00<00:02,  2.14it/s]
 29% 2/7 [00:00<00:02,  2.12it/s]
 43% 3/7 [00:01<00:01,  2.12it/s]
 57% 4/7 [00:01<00:01,  2.11it/s]
 71% 5/7 [00:02<00:00,  2.10it/s]
 86% 6/7 [00:02<00:00,  2.11it/s]
100% 7/7 [00:03<00:00,  2.11it/s]
Start generating .mp4 file
[ERROR:2@1459.072] global cap_ffmpeg_impl.hpp:2991 open Could not find encoder for codec_id=27, error: Encoder not found
[ERROR:2@1459.072] global cap_ffmpeg_impl.hpp:3066 open VIDEOIO/FFMPEG: Failed to initialize VideoWriter
[ERROR:2@1459.072] global cap.cpp:595 open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'


The generation is complete, the directory::outputs/mov2mov-videos/1679553729.mp4
Total progress: 100% 7/7 [00:03<00:00,  1.81it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 1888, in postprocess
    y = self.make_temp_copy_if_needed(y)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 379, in make_temp_copy_if_needed
    temp_file_path = self.get_temp_file_path(file_path)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 365, in get_temp_file_path
    file_hash = self.hash_file(file_path)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/mov2mov-videos/1679553729.mp4'

**Comment by Scholar01** [comment]
我最近没有在colab运行过,晚点我试试奥

**Comment by yerawell** [comment]
直接在setting里面再保存一下试试， 不用改设置，就是光保存可以看到有设置更改

**Comment by yerawell** [comment]
> 我也遇到同样问题
> The generation is complete, the directory::outputs/mov2mov-videos/1679653644.mp4
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
> output = await app.get_blocks().process_api(
> File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1018, in process_api
> data = self.postprocess_data(fn_index, result["prediction"], state)
> File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 956, in postprocess_data
> prediction_value = block.postprocess(prediction_value)
> File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 1888, in postprocess
> y = self.make_temp_copy_if_needed(y)
> File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 379, in make_temp_copy_if_needed
> temp_file_path = self.get_temp_file_path(file_path)
> File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 365, in get_temp_file_path
> file_hash = self.hash_file(file_path)
> File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 334, in hash_file
> with open(file_path, "rb") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'outputs/mov2mov-videos/1679653644.mp4'

去保存一下设置看看

**Comment by lloydsun** [comment]
你好，我昨天和今天都试过了，不仅保存了设置，也试过改变目录，都是这个错误

Start generating .mp4 file
[ERROR:0@454.037] global cap_ffmpeg_impl.hpp:2991 open Could not find encoder for codec_id=27, error: Encoder not found
[ERROR:0@454.037] global cap_ffmpeg_impl.hpp:3066 open VIDEOIO/FFMPEG: Failed to initialize VideoWriter
[ERROR:0@454.395] global cap.cpp:595 open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'


The generation is complete, the directory::outputs/mov2mov-videos/1679662523.mp4
Total progress: 100% 120/120 [00:26<00:00,  4.45it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 1888, in postprocess
    y = self.make_temp_copy_if_needed(y)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 379, in make_temp_copy_if_needed
    temp_file_path = self.get_temp_file_path(file_path)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 365, in get_temp_file_path
    file_hash = self.hash_file(file_path)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/mov2mov-videos/1679662523.mp4'

**Comment by lloydsun** [comment]
Encoder not found

好像是要我装 ffmpeg？请问应该怎么安装呢

**Comment by lloydsun** [comment]
补充一下，保存格式选择 H.264 时出现的上面的错误
如果选 mp4v 就能正确保存

**Comment by yerawell** [comment]
🤔

**Comment by ricohrh** [comment]
我也会 h.264无法保存

**Comment by Sostay** [comment]
解决了吗？我和你完全一样的问题，而且我不管是输出什么格式都一样报错……

**Comment by AIlearener** [comment]
我也是。。

**Comment by Sostay** [comment]
> 我也是。。

回退吧 4月15号的版本工作正常……
