### ISSUE TITLE
能否联系上下帧

### ISSUE THREAD

**Issue by 32MISOchipmunk** [Scholar01/sd-webui-mov2mov#3]

**Comment by Scholar01** [comment]
有这方面考虑，可以具体说说流程吗

**Comment by huazhuoyu** [comment]
比如参考这个AI 插帧工具，做模型融合？

**Comment by huazhuoyu** [comment]
自动补帧算法——RIFE的使用
https://zhuanlan.zhihu.com/p/565633270

**Comment by 32MISOchipmunk** [comment]
直接用上一帧渲染好的图片拿去img2img再加上当前帧的controlnet骨架试试?
这只是我的想法但我技术不足;=;

**Comment by Season02** [comment]
有人已经实现了，只是他的实现没有帮助生成视频

**Comment by Looong01** [comment]
> 有这方面考虑，可以具体说说流程吗

能否把这个脚本集成到插件中来实现上下帧的联系呢？https://xanthius.itch.io/multi-frame-rendering-for-stablediffusion

**Comment by Scholar01** [comment]
这个会显著增加显存. 一般机器都受不了
