### ISSUE TITLE
输出帧和视频都很模糊

### ISSUE THREAD

**Issue by WyHy** [Scholar01/sd-webui-mov2mov#33]
您好，我用这个插件的时候遇见输出结果很模糊的情况
在图生图的界面中验证测试的时候产出很清晰，但是相同的参数转到mov2mov就很模糊了，产出的视频只能看见一团影子，请问这个该怎么解决呢

**Comment by AlbieRWang** [comment]
同问 重绘高一点背景好像会被模糊，人物部分会和背景融在一起

**Comment by ChengBinJin** [comment]
same problem @Scholar01

**Comment by shenhaitao010** [comment]
same problem

**Comment by xuexuanyu** [comment]
same problem

**Comment by palvarez19** [comment]
I noticed that I get blurry results with samplers other than euler_a
