### ISSUE TITLE
缺失openh264-1.8.0-win64.dll

### ISSUE THREAD

**Issue by co2co** [Scholar01/sd-webui-mov2mov#36]
已根据插件提示自行下载，但是应该放到哪个位置？

**Comment by Sostay** [comment]
安装OpenCV  https://opencv.org/releases/
然后放到opencv的这个路径里——
![image](https://user-images.githubusercontent.com/6897274/232288201-ed735fa1-fc5a-4dfb-bf14-db8d9643aaaf.png)

**Comment by issiah-chain** [comment]
> 安装OpenCV https://opencv.org/releases/ 然后放到opencv的这个路径里—— ![image](https://user-images.githubusercontent.com/6897274/232288201-ed735fa1-fc5a-4dfb-bf14-db8d9643aaaf.png)

请问应该怎么安装OpenCV？官网说这是一个库合集，不是一个独立分发程序，我应该把这些文件放到哪个目录呢？

**Comment by Sostay** [comment]
> > 安装OpenCV https://opencv.org/releases/ 然后放到opencv的这个路径里—— ![image](https://user-images.githubusercontent.com/6897274/232288201-ed735fa1-fc5a-4dfb-bf14-db8d9643aaaf.png)
> 
> 请问应该怎么安装OpenCV？官网说这是一个库合集，不是一个独立分发程序，我应该把这些文件放到哪个目录呢？

https://github.com/Scholar01/sd-webui-mov2mov/issues/56 我好像说错了，你参考这个
