### ISSUE TITLE
Generate Movie Mode与ModNet使用报错

### ISSUE THREAD

**Issue by shenhaitao010** [Scholar01/sd-webui-mov2mov#39]
Generate Movie Mode使用H.264，报如下错误，视频生成失败：
[ERROR:0@39362.673] global cap_ffmpeg_impl.hpp:2991 open Could not find encoder for codec_id=27, error: Encoder not found
[ERROR:0@39362.673] global cap_ffmpeg_impl.hpp:3066 open VIDEOIO/FFMPEG: Failed to initialize VideoWriter
[ERROR:0@39362.674] global cap.cpp:595 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'

ModNet使用mobilenetv2_human_seg.ckpt模型，报如下错误，模型加载失败：
  File "/stable-diffusion-webui/extensions/sd-webui-mov2mov-master/scripts/m2m_modnet.py", line 33, in get_model
    modnet.load_state_dict(weights)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.backbone.model.features.0.0.weight", "

**Comment by DaidoujiChen** [comment]
你把 `mobilenetv2_human_seg.ckpt` 換成用 `modnet_photographic_portrait_matting.ckpt` 試試
