### ISSUE TITLE
Error running install.py for extension C:\Users\zach1\stable-diffusion-webui\extensions\mov2mov.

### ISSUE THREAD

**Issue by zark119** [Scholar01/sd-webui-mov2mov#45]
更新之后启动出现报错
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "C:\Users\zach1\stable-diffusion-webui\extensions\mov2mov\install.py", line 4, in <module>
    plat = platform.system().lower()
NameError: name 'platform' is not defined

**Comment by olivxr** [comment]
getting the same error here, thanks for posting, I'll be coming back for a solution

**Comment by KelsieSart** [comment]
import platform  加在这个文件中的 import launch 前后换行，都可以，
![image](https://user-images.githubusercontent.com/20436348/232787213-0b797ba2-783e-47e0-a23b-dcd1d2c4beda.png)
具体等老板的解决方案
