### ISSUE TITLE
install.py 启动报错 的临时解决方案

### ISSUE THREAD

**Issue by KelsieSart** [Scholar01/sd-webui-mov2mov#50]
platform.system().lower() error code
添加   import platform 在 install.py 中得 import launch 后面 或者前面 换行都可以， 临时解决方案， 具体解决方案以所有者得为准

**Comment by KelsieSart** [comment]
![image](https://user-images.githubusercontent.com/20436348/233052104-b0ff9250-a5e1-4e8a-9b68-2a0f2bc0f237.png)
into the file folder, modify the file "install.py" like this

**Comment by Scholar01** [comment]
这个是因为没仔细检查pr,我的错,已经修复
