### ISSUE TITLE
更新了新版本control net之后，mov2mov的control net不生效了

### ISSUE THREAD

**Issue by t505892790** [Scholar01/sd-webui-mov2mov#52]

**Comment by zark119** [comment]
同样的现象，开controlnet和不开出的图是一样的

**Comment by joinquan** [comment]
不知道是因为更新了哪个出的问题，昨天更新之后我的也是，没有任何报错

**Comment by zhangqizky** [comment]
确实是，同样的问题

**Comment by t505892790** [comment]
确认了是control net 1.1的问题，回退control net版本后就好了，望丁菩萨早日兼容1.1

**Comment by lengsehuoyan** [comment]
救救1.1

**Comment by zhangqizky** [comment]
不知道为什么我在这个代码库里面没有发现任何controlnet的东西啊，即使是之前的版本，controlnet又是如何生效的呢？

**Comment by zhangqizky** [comment]
> 确认了是control net 1.1的问题，回退control net版本后就好了，望丁菩萨早日兼容1.1

@t505892790 请问你是怎么回退到controlnet1.0的呀？

**Comment by zark119** [comment]
更新了controlnet，现在mov2mov也可以用了。默认的Noise multiplier 0，会让图很模糊。调高这个值可以变得清晰，但是闪烁也会变大

**Comment by zhangqizky** [comment]
> 

hello，请问你现在是controlnet1.1 可以用mov2mov了嘛？奇怪的作者这两天也没有动这个代码库，难道生效的部分是在controlnet那个插件里面...

**Comment by zark119** [comment]
> @zark119 hello，请问你现在是controlnet1.1 可以用mov2mov了嘛？奇怪的作者这两天也没有动这个代码库，难道生效的部分是在controlnet那个插件里面...

可以了

**Comment by Scholar01** [comment]
mov2mov并没有对control net做任何侵入啊.

**Comment by zhangqizky** [comment]
@Scholar01 嗯嗯，我搞明白了，我看到用的pipeline是这个，StableDiffusionProcessingImg2Img，以为和huggingface diffusers里面是一样的，其实webui已经重新定义了这个StableDiffusionProcessingImg2Img了，会check controlnet那个插件的状态，如果是开启的，就会使用controlnet

**Comment by lucasGuoCHY** [comment]
As a quick fix edit javascript/ui.js line 125. Replace with:

try{ gradioApp().getElementById(tabname + '_interrupting').style.display = showInterrupting?'block':'none';} catch(e){}

profit. You are welcome :-)

**Comment by zhangqizky** [comment]
您的邮件已收到，我会尽快回复，谢谢。张琦
