### ISSUE TITLE
openh264-1.8.0-win64

### ISSUE THREAD

**Issue by EKI-INDRADI** [Scholar01/sd-webui-mov2mov#56]
Failed to load OpenH264 library: openh264-1.8.0-win64.dll
        Please check environment and/or download library: https://github.com/cisco/openh264/releases

[libopenh264 @ 00000271524cd600] Incorrect library version loaded
[ERROR:0@3440.829] global cap_ffmpeg_impl.hpp:3049 open Could not open codec libopenh264, error: Unspecified error (-22)
[ERROR:0@3440.829] global cap_ffmpeg_impl.hpp:3066 open VIDEOIO/FFMPEG: Failed to initialize VideoWriter
The generation is complete, the directory::outputs/mov2mov-videos\1682419443.mp4
Total progress:  90%|███████████████████████████████████████████████████████▊      | 5544/6160 [57:19<06:22,  1.61it/s]
Total progress:  90%|███████████████████████████████████████████████████████▊      | 5544/6160 [57:19<04:17,  2.39it/s]

**Comment by danseman** [comment]
http://ciscobinary.openh264.org/openh264-1.8.0-win64.dll.bz2
Download and unzip the 
and paste it into the directory specified in the path.
It will be version checked, so it must be that version.
