### ISSUE TITLE
This is not compatible with vladmandic/automatic

### ISSUE THREAD

**Issue by DoDoExt** [Scholar01/sd-webui-mov2mov#58]
I'm not sure if the problem is on your end, or his, but I thought I'd let you know.

executing callback: E:\automatic\extensions\sd-webui-mov2mov\scripts\m2m_ui.py ui_tabs_callback: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ E:\automatic\modules\script_callbacks.py:142 in ui_tabs_callback                                                     │
│                                                                                                                      │
│   141 │   │   try:                                                                                                   │
│ ❱ 142 │   │   │   res += c.callback() or []                                                                          │
│   143 │   │   except Exception as e:                                                                                 │
│                                                                                                                      │
│ E:\automatic\extensions\sd-webui-mov2mov\scripts\m2m_ui.py:234 in on_ui_tabs                                         │
│                                                                                                                      │
│   233 │   │   │   │   │   │   │   res_switch_btn = ToolButton(value=switch_values_symbol, elem                       │
│ ❱ 234 │   │   │   │   │   │   │   if opts.dimensions_and_batch_together:                                             │
│   235 │   │   │   │   │   │   │   │   with gr.Column(elem_id=f"{id_part}_column_batch"):                             │
│                                                                                                                      │
│ E:\automatic\modules\shared.py:547 in __getattr__                                                                    │
│                                                                                                                      │
│   546 │   │                                                                                                          │
│ ❱ 547 │   │   return super(Options, self).__getattribute__(item)                                                     │
│   548                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Options' object has no attribute 'dimensions_and_batch_together'

https://github.com/vladmandic/automatic

**Comment by alexopus** [comment]
https://github.com/vladmandic/automatic/issues/542
