### ISSUE TITLE
【功能建议】图片帧支持自动clip反推关键词

### ISSUE THREAD

**Issue by neilwong2012** [Scholar01/sd-webui-mov2mov#6]
支持每张视频帧处理前，执行clip反推关键词，然后将关键词append到当前关键词中，这样视频的生成更加和内容吻合。

**Comment by huazhuoyu** [comment]
抖动问题和关键词关系不大，同样的参数和种子也会抖，感觉用视频插帧的模型做控制是个好方向。
https://github.com/n00mkrad/flowframes
https://zhuanlan.zhihu.com/p/565633270

**Comment by Scholar01** [comment]
考虑
