### ISSUE TITLE
preview issue

### ISSUE THREAD

**Issue by Foreist** [Scholar01/sd-webui-mov2mov#63]
python: 3.10.9  •  torch: 1.13.1+cu117  •  xformers: 0.0.17.dev449  •  gradio: 3.16.2
If you run mov2mov without using controlnet, you can see the preview, but if you add controlnet, you can't see the preview. 
controlnet version: 1.1.130

**Comment by Scholar01** [comment]
I'll check it out

**Comment by keithbandit98** [comment]
hi, me too but honesty i never seen a preview also without controlnet, pleas fix.. is very important the preview
