### ISSUE TITLE
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 4). Wanted outputs:     [gallery, video, textbox, html, html]]

### ISSUE THREAD

**Issue by xjq284** [Scholar01/sd-webui-mov2mov#64]
/Users/xjq284/automatic/modules/call_queue.py:59 in f                                                       │
│                                                                                                             │
│    58 │   │   │   │   pr.enable()                                                                           │
│ ❱  59 │   │   │   res = list(func(*args, **kwargs))                                                         │
│    60 │   │   │   if shared.cmd_opts.profile:                                                               │
│                                                                                                             │
│ /Users/xjq284/automatic/modules/call_queue.py:38 in f                                                       │
│                                                                                                             │
│    37 │   │   │   try:                                                                                      │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                           │
│    39 │   │   │   │   progress.record_results(id_task, res)                                                 │
│                                                                                                             │
│ /Users/xjq284/automatic/extensions/sd-webui-mov2mov/scripts/mov2mov.py:228 in mov2mov                       │
│                                                                                                             │
│   227 │                                                                                                     │
│ ❱ 228 │   if shared.cmd_opts.enable_console_prompts:                                                        │
│   229 │   │   print("shared11111111", shared)

**Comment by xjq284** [comment]
在webui.py开头加上: cmd_opts.enable_console_prompts=True就可以了

**Comment by hdwmp123** [comment]
加上了还是报同样的错误

**Comment by nervhuang** [comment]
在webui.py开头加上: cmd_opts.enable_console_prompts=True
結果一開始就出現錯誤連啟動都失敗，在Win10下執行的

  File "C:\stable-diffusion-webui\modules\launch_utils.py", line 330, in start
    import webui
  File "C:\stable-diffusion-webui\webui.py", line 3
    from __future__ import annotations
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
