### ISSUE TITLE
Mov2Mov上在 新版本 SD [5ab7f213]、 torch: 2.0.0+cu118、gradio: 3.28.1 ，失效。希能有解決方案 謝謝

### ISSUE THREAD

**Issue by xiaoooan** [Scholar01/sd-webui-mov2mov#65]
版本 : python: 3.10.5  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.28.1  •  commit: [5ab7f213]

我測試過 
第一個方法在新版SD [5ab7f213] - ControlNet v1.1.150和沒用ControlNet v1.1.150 在M2M輸出失效
第二個方法在舊版SD [22bcc7be] - 使用ControlNet v1.1.150 使用 M2M 能正常輸出

最終確定是 最新SD[5ab7f213]版本的關係還有torch: 2.0.0+cu118造成
請問有沒有解決方法和之後的更新呢? 謝謝

**Comment by w-e-w** [comment]
issues for extension should be reported to the extension repo
