### ISSUE TITLE
按照教学安装完成之后，扩展里找不到怎么回事 #24

### ISSUE THREAD

**Issue by dhs964057117** [Scholar01/sd-webui-mov2mov#67]
![image](https://github.com/Scholar01/sd-webui-mov2mov/assets/34617909/33dbdd33-9cb7-4205-bb4d-63884bc1e504)
![image](https://github.com/Scholar01/sd-webui-mov2mov/assets/34617909/f441bbfc-a31b-4a8f-9dd1-57e02f2a8e05)

**Comment by feijihaizaifei** [comment]
大重启

**Comment by Scholar01** [comment]
修好了
