### ISSUE TITLE
Got error while export video

### ISSUE THREAD

**Issue by rockstan2023** [Scholar01/sd-webui-mov2mov#71]
[libopenh264 @ 00000229ca959980] Incorrect library version loaded
[ERROR:0@616.405] global cap_ffmpeg_impl.hpp:3049 open Could not open codec libopenh264, error: Unspecified error (-22)
[ERROR:0@616.405] global cap_ffmpeg_impl.hpp:3066 open VIDEOIO/FFMPEG: Failed to initialize VideoWriter

**Comment by Scholar01** [comment]
fixed
