### ISSUE TITLE
Export video error

### ISSUE THREAD

**Issue by teng231** [Scholar01/sd-webui-mov2mov#72]
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/mov2mov-videos/1685098224.mp4'

**Comment by 93041025** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'outputs/mov2mov-videos/1685098224.mp4'

same issue. i installed ffmpeg but still remain same. mp4v has no problem but h.264 has a problem.

**Comment by sordidloam** [comment]
Same for me if choosing h.264 "FileNotFoundError: [Errno 2] No such file or directory: 'outputs/mov2mov-videos\\1688377331.mp4"

**Comment by C4l1b3r** [comment]
Oh good July and no fix lol

**Comment by YellowRoseCx** [comment]
why'd this get marked as closed?
