### ISSUE TITLE
Is mov2mov still supported?

### ISSUE THREAD

**Issue by dkamajix** [Scholar01/sd-webui-mov2mov#89]
Im having issues with latest Controlnet. getting warnings every time I have both extensions activated using a1111 v1.52.
Anyone know how to fix this or if this awesome extension is still supported?

**Comment by ALEXOTANO** [comment]
did you manage to solve it?

**Comment by RuneGjerde** [comment]
try this fork https://github.com/DavG25/sd-webui-mov2mov works great for me,

**Comment by Scholar01** [comment]
fixed
