### ISSUE TITLE
Errors after update

### ISSUE THREAD

**Issue by C4l1b3r** [Scholar01/sd-webui-mov2mov#93]
![Screenshot_20230923_065754_RVNC Viewer](https://github.com/Scholar01/sd-webui-mov2mov/assets/17440115/047e3dc5-1e16-407f-97e8-a48c3b4fdbe5)

Upon update I recieve these

**Comment by Scholar01** [comment]
Please completely delete and reinstall

**Comment by C4l1b3r** [comment]
Deleted and reinstalled same errors. I can try to delete the venv and start over that way.
