### ISSUE TITLE
Preview image is super small (can't enlarge_

### ISSUE THREAD

**Issue by CCpt5** [Scholar01/sd-webui-mov2mov#97]
Sorry if this is user error, but at the moment I'm unable to increase the size of the preview image/video and it's extremely small. If this isn't something I'm doing incorrectly is there a way this can be fixed? 

Thanks for continuing to develop this extension!

![545454151](https://github.com/Scholar01/sd-webui-mov2mov/assets/37972078/6d17ae83-73a6-46bf-ad58-2afe1b55a514)

**Comment by Scholar01** [comment]
This preview is correct
